### ISSUE TITLE
Training Beacon - KeepAlive Failure

### ISSUE THREAD

**Issue by lucanos** [NSWSESMembers/Lighthouse#19]
Evening, Gents.

Whilst reading the codebase, I noticed that Lighthouse is hardcoded to perform KeepAlive calls for Production Beacon only (['background.js' Line 5] (https://github.com/OSPFNeighbour/Lighthouse/blob/master/background.js#L5).)

I toyed with a solution where the `chrome.runtime` message passed, along with the activity flag, the location of the calling page and then set the `baseUri` variable to the appropriate host, but then I found another issue when (in the somewhat unlikely event that a user is logged into Training Beacon and Production Beacon on the same browser), the KeepAlive system would only keep the session associated with the most recent `chrome.runtime` event active.

Not sure what the solution is here, aside from trying to keep Production and Training alive each time (which would be an un-necessary call to Training in 99% of usage cases).

Thoughts?

**Comment by sdunster** [comment]
I plan to refactor this. I think the correct solution is to only kick off the keep alive timer after a page from either has been loaded. Every time we load a page or make an API call we send a message to the background script and so we can tell it which environment we are operating in (or both!).

I'd hold off on making any big changes right now simply because I've got a really big restructure coming hopefully sometime over the next 24 hours and you probably don't want to have to deal with merge conflicts.
